//define.h
#include<LPC21xx.h>
#define SETBIT(WORD,BITPOS)              (WORD |=1<<BITPOS) 
#define	SSETBIT(WORD,BITPOS)			 (WORD  =1<<BITPOS) 

#define	CLRBIT(WORD,BITPOS)				 (WORD &=~(1<<BITPOS)) 
#define	SCLRBIT(WORD,BITPOS)			 (WORD  =1<<BITPOS) 

#define	CPLBIT(WORD,BITPOS)				 (WORD ^=1<<BITPOS) 

#define	READBIT(WORD,BITPOS)			 ((WORD>>BITPOS)&1) 

#define	WRITEBYTE(WORD,STARTBITPOS,BYTE)           (WORD=((WORD&~(255<<STARTBITPOS))|(BYTE<<STARTBITPOS)))

#define	READWRITEBIT(WORD,DBIT,SBIT)		       (WORD=((WORD&~(1<<DBIT))|((WORD>>SBIT)&1)<<DBIT))

#define READNIBBLE(WORD,STARTBITPOS)               ((WORD>>STARTBITPOS)&15)

#define WRITENIBBLE(WORD,STARTBITPOS,NIBBLE) 	   (WORD=((WORD&~(15<<STARTBITPOS))|(NIBBLE<<STARTBITPOS)))



 //ADD MORE AS AND 
